name: cross browser testing 

on:
  push:
    branches:
      - "integration"
      - "main"
  pull_request:
    types: [opened,reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: actions/setup-node@v3

      - name: Build Docker Image
        run: docker build -t cypress-tests .

      - name: Run Cypress Tests
        run: |
          docker run --rm -e cypress-tests
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: e2e/cypress/screenshots e2e/cypress/videos # Adjust the paths based on your project structure