name: cross browser testing 

on:
  push:
    branches:
      - "integration"
      - "main"
  pull_request:
    types: [opened,reopened]

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'edge', 'electron']
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cypress-tests .

      - name: Run Cypress Tests
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          docker run --rm -e BROWSER=$BROWSER cypress-tests

        # env:
        #   BROWSER: ${{ matrix.browser }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: /e2e/cypress/screenshots /e2e/cypress/videos # Adjust the paths based on your project structure

      # - name: Cypress install
      #   uses: cypress-io/github-action@v6
      #   with:
      #     runTests: false
      
      # - name: Cypress run
      #   run: |
      #     if [ "${{ matrix.browser }}" == "electron" ]; then
      #       npm run test
      #     else
      #       npm run test -- --browser "${{ matrix.browser }}"
      #     fi

