name: cross browser testing 

on:
  push:
    branches:
      - "integration"
      - "main"
  pull_request:
    types: [opened,reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: actions/setup-node@v3

      - name: Build Docker Image
        run: |
          docker build -t myimg .
          docker images

      - name: Run Cypress Tests in Docker Container
        run: |
          docker run -it --rm \
            -v ./artifacts/edge:/e2e/cypress/screenshots \
            -w /e2e \
            myimg

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/videos