# name: Cypress Tests using Cypress Docker Image

# on: push

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     container:
#       image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           build: npm run build
#           start: npm start
#           browser: chrome

name: cross browser testing 

on:
  push:
    branches:
      - "integration"
      - "main"
  pull_request:
    types: [opened,reopened]

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox', 'edge', 'electron']
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      
      - name: Cypress run
        run: |
          if [ "${{ matrix.browser }}" == "electron" ]; then
            npm run test
          else
            npm run test -- --browser "${{ matrix.browser }}"
          fi

      # - name: Upload Chrome artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: chrome-artifacts
      #     path: |
      #       ./artifacts/chrome/videos
      #       ./artifacts/chrome/screenshots
      #     if-no-files-found: ignore
      #     retention-days: 5