name: cross browser testing 

on:
  push:
    branches:
      - "integration"
      - "main"
  pull_request:
    types: [opened,reopened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v2.2.7
        with:
          runsTests: false #disable running tests within install job. We are just caching it so we can reuse it multiple times
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: dist
  
  cypress-run:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        container: [1,2,3,4]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download the build folder
        uses: actions/download-artifacts@v3
        with:
          name: build
        
      - name: Cypress run
        uses: cypress-io/github-action@v2.2.7
        with:
          record: true
          parallel: true
          group: 'UI-Chrome'
          start: npm start
